//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DroidUpc.UpcSvc {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IUpcSvc", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TCSRBase))]
    public partial class UpcSvc : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetLastScanDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDvdScanInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDvdScanInfosFromTitleOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateDvdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBookScanInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBookScanInfosFromTitleOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateBookScanOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWineScanInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DrinkWineOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUpcLastScanDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchTitleFromGenericUPCOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchTitleFromISBN13OperationCompleted;
        
        private System.Threading.SendOrPostCallback TestLogOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UpcSvc() {
            this.Url = "http://thetasoft2.azurewebsites.net/UpcSvc/UpcSvc.svc/soap";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetLastScanDateCompletedEventHandler GetLastScanDateCompleted;
        
        /// <remarks/>
        public event GetDvdScanInfoCompletedEventHandler GetDvdScanInfoCompleted;
        
        /// <remarks/>
        public event GetDvdScanInfosFromTitleCompletedEventHandler GetDvdScanInfosFromTitleCompleted;
        
        /// <remarks/>
        public event CreateDvdCompletedEventHandler CreateDvdCompleted;
        
        /// <remarks/>
        public event GetBookScanInfoCompletedEventHandler GetBookScanInfoCompleted;
        
        /// <remarks/>
        public event GetBookScanInfosFromTitleCompletedEventHandler GetBookScanInfosFromTitleCompleted;
        
        /// <remarks/>
        public event CreateBookCompletedEventHandler CreateBookCompleted;
        
        /// <remarks/>
        public event UpdateBookScanCompletedEventHandler UpdateBookScanCompleted;
        
        /// <remarks/>
        public event GetWineScanInfoCompletedEventHandler GetWineScanInfoCompleted;
        
        /// <remarks/>
        public event DrinkWineCompletedEventHandler DrinkWineCompleted;
        
        /// <remarks/>
        public event UpdateUpcLastScanDateCompletedEventHandler UpdateUpcLastScanDateCompleted;
        
        /// <remarks/>
        public event FetchTitleFromGenericUPCCompletedEventHandler FetchTitleFromGenericUPCCompleted;
        
        /// <remarks/>
        public event FetchTitleFromISBN13CompletedEventHandler FetchTitleFromISBN13Completed;
        
        /// <remarks/>
        public event TestLogCompletedEventHandler TestLogCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUpcSvc/GetLastScanDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public USR_String GetLastScanDate([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sScanCode) {
            object[] results = this.Invoke("GetLastScanDate", new object[] {
                        sScanCode});
            return ((USR_String)(results[0]));
        }
        
        /// <remarks/>
        public void GetLastScanDateAsync(string sScanCode) {
            this.GetLastScanDateAsync(sScanCode, null);
        }
        
        /// <remarks/>
        public void GetLastScanDateAsync(string sScanCode, object userState) {
            if ((this.GetLastScanDateOperationCompleted == null)) {
                this.GetLastScanDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLastScanDateOperationCompleted);
            }
            this.InvokeAsync("GetLastScanDate", new object[] {
                        sScanCode}, this.GetLastScanDateOperationCompleted, userState);
        }
        
        private void OnGetLastScanDateOperationCompleted(object arg) {
            if ((this.GetLastScanDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLastScanDateCompleted(this, new GetLastScanDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUpcSvc/GetDvdScanInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public USR_DvdInfo GetDvdScanInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sScanCode) {
            object[] results = this.Invoke("GetDvdScanInfo", new object[] {
                        sScanCode});
            return ((USR_DvdInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetDvdScanInfoAsync(string sScanCode) {
            this.GetDvdScanInfoAsync(sScanCode, null);
        }
        
        /// <remarks/>
        public void GetDvdScanInfoAsync(string sScanCode, object userState) {
            if ((this.GetDvdScanInfoOperationCompleted == null)) {
                this.GetDvdScanInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDvdScanInfoOperationCompleted);
            }
            this.InvokeAsync("GetDvdScanInfo", new object[] {
                        sScanCode}, this.GetDvdScanInfoOperationCompleted, userState);
        }
        
        private void OnGetDvdScanInfoOperationCompleted(object arg) {
            if ((this.GetDvdScanInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDvdScanInfoCompleted(this, new GetDvdScanInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUpcSvc/GetDvdScanInfosFromTitle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public USR_DvdInfoList GetDvdScanInfosFromTitle([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sTitleSubstring) {
            object[] results = this.Invoke("GetDvdScanInfosFromTitle", new object[] {
                        sTitleSubstring});
            return ((USR_DvdInfoList)(results[0]));
        }
        
        /// <remarks/>
        public void GetDvdScanInfosFromTitleAsync(string sTitleSubstring) {
            this.GetDvdScanInfosFromTitleAsync(sTitleSubstring, null);
        }
        
        /// <remarks/>
        public void GetDvdScanInfosFromTitleAsync(string sTitleSubstring, object userState) {
            if ((this.GetDvdScanInfosFromTitleOperationCompleted == null)) {
                this.GetDvdScanInfosFromTitleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDvdScanInfosFromTitleOperationCompleted);
            }
            this.InvokeAsync("GetDvdScanInfosFromTitle", new object[] {
                        sTitleSubstring}, this.GetDvdScanInfosFromTitleOperationCompleted, userState);
        }
        
        private void OnGetDvdScanInfosFromTitleOperationCompleted(object arg) {
            if ((this.GetDvdScanInfosFromTitleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDvdScanInfosFromTitleCompleted(this, new GetDvdScanInfosFromTitleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUpcSvc/CreateDvd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public USR CreateDvd([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sScanCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sTitle) {
            object[] results = this.Invoke("CreateDvd", new object[] {
                        sScanCode,
                        sTitle});
            return ((USR)(results[0]));
        }
        
        /// <remarks/>
        public void CreateDvdAsync(string sScanCode, string sTitle) {
            this.CreateDvdAsync(sScanCode, sTitle, null);
        }
        
        /// <remarks/>
        public void CreateDvdAsync(string sScanCode, string sTitle, object userState) {
            if ((this.CreateDvdOperationCompleted == null)) {
                this.CreateDvdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDvdOperationCompleted);
            }
            this.InvokeAsync("CreateDvd", new object[] {
                        sScanCode,
                        sTitle}, this.CreateDvdOperationCompleted, userState);
        }
        
        private void OnCreateDvdOperationCompleted(object arg) {
            if ((this.CreateDvdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDvdCompleted(this, new CreateDvdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUpcSvc/GetBookScanInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public USR_BookInfo GetBookScanInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sScanCode) {
            object[] results = this.Invoke("GetBookScanInfo", new object[] {
                        sScanCode});
            return ((USR_BookInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetBookScanInfoAsync(string sScanCode) {
            this.GetBookScanInfoAsync(sScanCode, null);
        }
        
        /// <remarks/>
        public void GetBookScanInfoAsync(string sScanCode, object userState) {
            if ((this.GetBookScanInfoOperationCompleted == null)) {
                this.GetBookScanInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBookScanInfoOperationCompleted);
            }
            this.InvokeAsync("GetBookScanInfo", new object[] {
                        sScanCode}, this.GetBookScanInfoOperationCompleted, userState);
        }
        
        private void OnGetBookScanInfoOperationCompleted(object arg) {
            if ((this.GetBookScanInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBookScanInfoCompleted(this, new GetBookScanInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUpcSvc/GetBookScanInfosFromTitle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public USR_BookInfoList GetBookScanInfosFromTitle([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sTitleSubstring) {
            object[] results = this.Invoke("GetBookScanInfosFromTitle", new object[] {
                        sTitleSubstring});
            return ((USR_BookInfoList)(results[0]));
        }
        
        /// <remarks/>
        public void GetBookScanInfosFromTitleAsync(string sTitleSubstring) {
            this.GetBookScanInfosFromTitleAsync(sTitleSubstring, null);
        }
        
        /// <remarks/>
        public void GetBookScanInfosFromTitleAsync(string sTitleSubstring, object userState) {
            if ((this.GetBookScanInfosFromTitleOperationCompleted == null)) {
                this.GetBookScanInfosFromTitleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBookScanInfosFromTitleOperationCompleted);
            }
            this.InvokeAsync("GetBookScanInfosFromTitle", new object[] {
                        sTitleSubstring}, this.GetBookScanInfosFromTitleOperationCompleted, userState);
        }
        
        private void OnGetBookScanInfosFromTitleOperationCompleted(object arg) {
            if ((this.GetBookScanInfosFromTitleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBookScanInfosFromTitleCompleted(this, new GetBookScanInfosFromTitleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUpcSvc/CreateBook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public USR CreateBook([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sScanCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sTitle, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sLocation) {
            object[] results = this.Invoke("CreateBook", new object[] {
                        sScanCode,
                        sTitle,
                        sLocation});
            return ((USR)(results[0]));
        }
        
        /// <remarks/>
        public void CreateBookAsync(string sScanCode, string sTitle, string sLocation) {
            this.CreateBookAsync(sScanCode, sTitle, sLocation, null);
        }
        
        /// <remarks/>
        public void CreateBookAsync(string sScanCode, string sTitle, string sLocation, object userState) {
            if ((this.CreateBookOperationCompleted == null)) {
                this.CreateBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateBookOperationCompleted);
            }
            this.InvokeAsync("CreateBook", new object[] {
                        sScanCode,
                        sTitle,
                        sLocation}, this.CreateBookOperationCompleted, userState);
        }
        
        private void OnCreateBookOperationCompleted(object arg) {
            if ((this.CreateBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateBookCompleted(this, new CreateBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUpcSvc/UpdateBookScan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public USR UpdateBookScan([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sScanCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sTitle, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sLocation) {
            object[] results = this.Invoke("UpdateBookScan", new object[] {
                        sScanCode,
                        sTitle,
                        sLocation});
            return ((USR)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateBookScanAsync(string sScanCode, string sTitle, string sLocation) {
            this.UpdateBookScanAsync(sScanCode, sTitle, sLocation, null);
        }
        
        /// <remarks/>
        public void UpdateBookScanAsync(string sScanCode, string sTitle, string sLocation, object userState) {
            if ((this.UpdateBookScanOperationCompleted == null)) {
                this.UpdateBookScanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateBookScanOperationCompleted);
            }
            this.InvokeAsync("UpdateBookScan", new object[] {
                        sScanCode,
                        sTitle,
                        sLocation}, this.UpdateBookScanOperationCompleted, userState);
        }
        
        private void OnUpdateBookScanOperationCompleted(object arg) {
            if ((this.UpdateBookScanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateBookScanCompleted(this, new UpdateBookScanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUpcSvc/GetWineScanInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public USR_WineInfo GetWineScanInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sScanCode) {
            object[] results = this.Invoke("GetWineScanInfo", new object[] {
                        sScanCode});
            return ((USR_WineInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetWineScanInfoAsync(string sScanCode) {
            this.GetWineScanInfoAsync(sScanCode, null);
        }
        
        /// <remarks/>
        public void GetWineScanInfoAsync(string sScanCode, object userState) {
            if ((this.GetWineScanInfoOperationCompleted == null)) {
                this.GetWineScanInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWineScanInfoOperationCompleted);
            }
            this.InvokeAsync("GetWineScanInfo", new object[] {
                        sScanCode}, this.GetWineScanInfoOperationCompleted, userState);
        }
        
        private void OnGetWineScanInfoOperationCompleted(object arg) {
            if ((this.GetWineScanInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWineScanInfoCompleted(this, new GetWineScanInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUpcSvc/DrinkWine", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public USR DrinkWine([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sScanCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sWine, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sVintage, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sNotes) {
            object[] results = this.Invoke("DrinkWine", new object[] {
                        sScanCode,
                        sWine,
                        sVintage,
                        sNotes});
            return ((USR)(results[0]));
        }
        
        /// <remarks/>
        public void DrinkWineAsync(string sScanCode, string sWine, string sVintage, string sNotes) {
            this.DrinkWineAsync(sScanCode, sWine, sVintage, sNotes, null);
        }
        
        /// <remarks/>
        public void DrinkWineAsync(string sScanCode, string sWine, string sVintage, string sNotes, object userState) {
            if ((this.DrinkWineOperationCompleted == null)) {
                this.DrinkWineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDrinkWineOperationCompleted);
            }
            this.InvokeAsync("DrinkWine", new object[] {
                        sScanCode,
                        sWine,
                        sVintage,
                        sNotes}, this.DrinkWineOperationCompleted, userState);
        }
        
        private void OnDrinkWineOperationCompleted(object arg) {
            if ((this.DrinkWineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DrinkWineCompleted(this, new DrinkWineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUpcSvc/UpdateUpcLastScanDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public USR UpdateUpcLastScanDate([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sScanCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sTitle) {
            object[] results = this.Invoke("UpdateUpcLastScanDate", new object[] {
                        sScanCode,
                        sTitle});
            return ((USR)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUpcLastScanDateAsync(string sScanCode, string sTitle) {
            this.UpdateUpcLastScanDateAsync(sScanCode, sTitle, null);
        }
        
        /// <remarks/>
        public void UpdateUpcLastScanDateAsync(string sScanCode, string sTitle, object userState) {
            if ((this.UpdateUpcLastScanDateOperationCompleted == null)) {
                this.UpdateUpcLastScanDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUpcLastScanDateOperationCompleted);
            }
            this.InvokeAsync("UpdateUpcLastScanDate", new object[] {
                        sScanCode,
                        sTitle}, this.UpdateUpcLastScanDateOperationCompleted, userState);
        }
        
        private void OnUpdateUpcLastScanDateOperationCompleted(object arg) {
            if ((this.UpdateUpcLastScanDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUpcLastScanDateCompleted(this, new UpdateUpcLastScanDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUpcSvc/FetchTitleFromGenericUPC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FetchTitleFromGenericUPC([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sCode) {
            object[] results = this.Invoke("FetchTitleFromGenericUPC", new object[] {
                        sCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FetchTitleFromGenericUPCAsync(string sCode) {
            this.FetchTitleFromGenericUPCAsync(sCode, null);
        }
        
        /// <remarks/>
        public void FetchTitleFromGenericUPCAsync(string sCode, object userState) {
            if ((this.FetchTitleFromGenericUPCOperationCompleted == null)) {
                this.FetchTitleFromGenericUPCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchTitleFromGenericUPCOperationCompleted);
            }
            this.InvokeAsync("FetchTitleFromGenericUPC", new object[] {
                        sCode}, this.FetchTitleFromGenericUPCOperationCompleted, userState);
        }
        
        private void OnFetchTitleFromGenericUPCOperationCompleted(object arg) {
            if ((this.FetchTitleFromGenericUPCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchTitleFromGenericUPCCompleted(this, new FetchTitleFromGenericUPCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUpcSvc/FetchTitleFromISBN13", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FetchTitleFromISBN13([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sCode) {
            object[] results = this.Invoke("FetchTitleFromISBN13", new object[] {
                        sCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FetchTitleFromISBN13Async(string sCode) {
            this.FetchTitleFromISBN13Async(sCode, null);
        }
        
        /// <remarks/>
        public void FetchTitleFromISBN13Async(string sCode, object userState) {
            if ((this.FetchTitleFromISBN13OperationCompleted == null)) {
                this.FetchTitleFromISBN13OperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchTitleFromISBN13OperationCompleted);
            }
            this.InvokeAsync("FetchTitleFromISBN13", new object[] {
                        sCode}, this.FetchTitleFromISBN13OperationCompleted, userState);
        }
        
        private void OnFetchTitleFromISBN13OperationCompleted(object arg) {
            if ((this.FetchTitleFromISBN13Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchTitleFromISBN13Completed(this, new FetchTitleFromISBN13CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUpcSvc/TestLog", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public USR TestLog() {
            object[] results = this.Invoke("TestLog", new object[0]);
            return ((USR)(results[0]));
        }
        
        /// <remarks/>
        public void TestLogAsync() {
            this.TestLogAsync(null);
        }
        
        /// <remarks/>
        public void TestLogAsync(object userState) {
            if ((this.TestLogOperationCompleted == null)) {
                this.TestLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestLogOperationCompleted);
            }
            this.InvokeAsync("TestLog", new object[0], this.TestLogOperationCompleted, userState);
        }
        
        private void OnTestLogOperationCompleted(object arg) {
            if ((this.TestLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestLogCompleted(this, new TestLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UpcSvc")]
    public partial class USR_String : TUSROfstring {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(USR_String))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UpcSvc")]
    public partial class TUSROfstring : TCSRBase {
        
        private string theValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TheValue {
            get {
                return this.theValueField;
            }
            set {
                this.theValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TUSROfWineInfo9_SjqeMlk))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(USR_WineInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TUSROfArrayOfBookInfo9_SjqeMlk))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(USR_BookInfoList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TUSROfBookInfo9_SjqeMlk))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(USR_BookInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(USR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TUSROfArrayOfDvdInfo9_SjqeMlk))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(USR_DvdInfoList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TUSROfDvdInfo9_SjqeMlk))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(USR_DvdInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TUSROfstring))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(USR_String))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UpcSvc")]
    public partial class TCSRBase {
        
        private string correlationIDField;
        
        private string reasonField;
        
        private bool resultField;
        
        private bool resultFieldSpecified;
        
        /// <remarks/>
        public string CorrelationID {
            get {
                return this.correlationIDField;
            }
            set {
                this.correlationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        public bool Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResultSpecified {
            get {
                return this.resultFieldSpecified;
            }
            set {
                this.resultFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UpcSvc")]
    public partial class WineInfo {
        
        private string codeField;
        
        private System.DateTime firstScanField;
        
        private bool firstScanFieldSpecified;
        
        private System.DateTime lastScanField;
        
        private bool lastScanFieldSpecified;
        
        private string notesField;
        
        private string vintageField;
        
        private string wineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FirstScan {
            get {
                return this.firstScanField;
            }
            set {
                this.firstScanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FirstScanSpecified {
            get {
                return this.firstScanFieldSpecified;
            }
            set {
                this.firstScanFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastScan {
            get {
                return this.lastScanField;
            }
            set {
                this.lastScanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastScanSpecified {
            get {
                return this.lastScanFieldSpecified;
            }
            set {
                this.lastScanFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Vintage {
            get {
                return this.vintageField;
            }
            set {
                this.vintageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Wine {
            get {
                return this.wineField;
            }
            set {
                this.wineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UpcSvc")]
    public partial class BookInfo {
        
        private string codeField;
        
        private System.DateTime firstScanField;
        
        private bool firstScanFieldSpecified;
        
        private System.DateTime lastScanField;
        
        private bool lastScanFieldSpecified;
        
        private string locationField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FirstScan {
            get {
                return this.firstScanField;
            }
            set {
                this.firstScanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FirstScanSpecified {
            get {
                return this.firstScanFieldSpecified;
            }
            set {
                this.firstScanFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastScan {
            get {
                return this.lastScanField;
            }
            set {
                this.lastScanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastScanSpecified {
            get {
                return this.lastScanFieldSpecified;
            }
            set {
                this.lastScanFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UpcSvc")]
    public partial class DvdInfo {
        
        private string codeField;
        
        private System.DateTime firstScanField;
        
        private bool firstScanFieldSpecified;
        
        private System.DateTime lastScanField;
        
        private bool lastScanFieldSpecified;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FirstScan {
            get {
                return this.firstScanField;
            }
            set {
                this.firstScanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FirstScanSpecified {
            get {
                return this.firstScanFieldSpecified;
            }
            set {
                this.firstScanFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastScan {
            get {
                return this.lastScanField;
            }
            set {
                this.lastScanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastScanSpecified {
            get {
                return this.lastScanFieldSpecified;
            }
            set {
                this.lastScanFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(USR_WineInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UpcSvc")]
    public partial class TUSROfWineInfo9_SjqeMlk : TCSRBase {
        
        private WineInfo theValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WineInfo TheValue {
            get {
                return this.theValueField;
            }
            set {
                this.theValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UpcSvc")]
    public partial class USR_WineInfo : TUSROfWineInfo9_SjqeMlk {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(USR_BookInfoList))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UpcSvc")]
    public partial class TUSROfArrayOfBookInfo9_SjqeMlk : TCSRBase {
        
        private BookInfo[] theValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public BookInfo[] TheValue {
            get {
                return this.theValueField;
            }
            set {
                this.theValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UpcSvc")]
    public partial class USR_BookInfoList : TUSROfArrayOfBookInfo9_SjqeMlk {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(USR_BookInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UpcSvc")]
    public partial class TUSROfBookInfo9_SjqeMlk : TCSRBase {
        
        private BookInfo theValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BookInfo TheValue {
            get {
                return this.theValueField;
            }
            set {
                this.theValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UpcSvc")]
    public partial class USR_BookInfo : TUSROfBookInfo9_SjqeMlk {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UpcSvc")]
    public partial class USR : TCSRBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(USR_DvdInfoList))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UpcSvc")]
    public partial class TUSROfArrayOfDvdInfo9_SjqeMlk : TCSRBase {
        
        private DvdInfo[] theValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public DvdInfo[] TheValue {
            get {
                return this.theValueField;
            }
            set {
                this.theValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UpcSvc")]
    public partial class USR_DvdInfoList : TUSROfArrayOfDvdInfo9_SjqeMlk {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(USR_DvdInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UpcSvc")]
    public partial class TUSROfDvdInfo9_SjqeMlk : TCSRBase {
        
        private DvdInfo theValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DvdInfo TheValue {
            get {
                return this.theValueField;
            }
            set {
                this.theValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/UpcSvc")]
    public partial class USR_DvdInfo : TUSROfDvdInfo9_SjqeMlk {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetLastScanDateCompletedEventHandler(object sender, GetLastScanDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLastScanDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLastScanDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public USR_String Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((USR_String)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetDvdScanInfoCompletedEventHandler(object sender, GetDvdScanInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDvdScanInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDvdScanInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public USR_DvdInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((USR_DvdInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetDvdScanInfosFromTitleCompletedEventHandler(object sender, GetDvdScanInfosFromTitleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDvdScanInfosFromTitleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDvdScanInfosFromTitleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public USR_DvdInfoList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((USR_DvdInfoList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreateDvdCompletedEventHandler(object sender, CreateDvdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateDvdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateDvdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public USR Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((USR)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetBookScanInfoCompletedEventHandler(object sender, GetBookScanInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBookScanInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBookScanInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public USR_BookInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((USR_BookInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetBookScanInfosFromTitleCompletedEventHandler(object sender, GetBookScanInfosFromTitleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBookScanInfosFromTitleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBookScanInfosFromTitleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public USR_BookInfoList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((USR_BookInfoList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreateBookCompletedEventHandler(object sender, CreateBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public USR Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((USR)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateBookScanCompletedEventHandler(object sender, UpdateBookScanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateBookScanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateBookScanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public USR Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((USR)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetWineScanInfoCompletedEventHandler(object sender, GetWineScanInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWineScanInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWineScanInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public USR_WineInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((USR_WineInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DrinkWineCompletedEventHandler(object sender, DrinkWineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DrinkWineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DrinkWineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public USR Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((USR)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateUpcLastScanDateCompletedEventHandler(object sender, UpdateUpcLastScanDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUpcLastScanDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUpcLastScanDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public USR Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((USR)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void FetchTitleFromGenericUPCCompletedEventHandler(object sender, FetchTitleFromGenericUPCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchTitleFromGenericUPCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchTitleFromGenericUPCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void FetchTitleFromISBN13CompletedEventHandler(object sender, FetchTitleFromISBN13CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchTitleFromISBN13CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchTitleFromISBN13CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void TestLogCompletedEventHandler(object sender, TestLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public USR Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((USR)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591